version: "3"
services:
  api:
    build: ./docker/api
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - .:/usr/local/rust-simple-sns-api
    working_dir: /usr/local/rust-simple-sns-api
    tty: true
    environment:
      # volume内にビルドするとコンパイルが遅くなるのでvolume外でビルド
      CARGO_BUILD_TARGET_DIR: /target
    depends_on:
      - db

  db:
    image: mysql:8.0.22
    platform: linux/x86_64
    ports:
      - "${DB_PORT:-3306}:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: rust_simple_sns
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - rust-simple-sns-mysql-data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d

volumes:
  rust-simple-sns-mysql-data: